### ISSUE TITLE
Combattre le spam à l'inscription

### ISSUE THREAD

**Issue by JulienPalard** [AFPy/infra#15]
On se prend des milliers de demandes d'inscriptions à afpy-web, pour rien.

On est pas les seuls :
 - https://www.ralfj.de/blog/2018/06/02/mailman-subscription-spam.html
 - https://www.ralfj.de/blog/2018/06/10/mailman-subscription-spam-continued.html

J'ai configuré SUBSCRIBE_FORM_SECRET aujourd'hui.

**Comment by JulienPalard** [comment]
En ligne de commande depuis la jail mailman, depuis `/usr/local/mailman/bin/` on peut faire un `./list_requests -l afpy-web -H` puis un `D all` pour tous les virer.

**Comment by Seluj78** [comment]
Here are two scripts to select all requests. Be sure to accept all legits one firsts.

One is for mail sub requests and the other one for mail send

https://gist.github.com/Seluj78/ec7f0f3dd8681631021982714ec9a8c7

https://gist.github.com/Seluj78/9d06c429a0a9623fb986965f7f05e210

**Comment by JulienPalard** [comment]
Pour le moment ça va mieux, le SUBSCRIBE_FORM_SECRET a fait son effet.
