### ISSUE TITLE
Site pour traductions

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [AFPy/infra#17]
# Comment un site peut améliorer la traduction?

- vitesse
- contribution par mobile
- motivation

# Choix site:

- Plantoon: https://github.com/mozilla/pontoon
- Site custom

# FaQ

### Sur Github on peut filtrer les PR
On doit avoir un système de modération sur le site avec option rejet avec message

**Comment by Seluj78** [comment]
Yes ! J'y ai déjà réfléchis et je pensais aussi que ça serait une bonne idée! Et ça devrais pas être trop compliqué à faire, multi languages, custom pour python, bref carrément faisable :) 

cc @JulienPalard

**Comment by Abdur-rahmaanJ** [comment]
@Seluj78 M Julien est au courant vu qu'il m'a demander de mettre l'idée ici pour voir ce que pense les gens

**Comment by JulienPalard** [comment]
Ça vient avec une app pour tablette ?

**Comment by Abdur-rahmaanJ** [comment]
@JulienPalard deux options:

- PWA qui l'installe comme une app native
- Mobile app avec webview pour display le site
donc ouii

**Comment by Seluj78** [comment]
@JulienPalard si c'est fait avec un frontend responsive ca sera une webapp qui fonctionnera partout :D

**Comment by Seluj78** [comment]
Perso le back en Python/Flask avec une DB avec peewee je peux faire ça assez rapidement si on a des specs précises, maintenant faut juste trouver un/des devs front 🤣

**Comment by JulienPalard** [comment]
Je ferme cette issue inactive : je doute qu'il soit nécessaire d'implémenter quelque chose de nouveau (cf. pontoon), et je remets en doute que ça accélère vraiment la traduction.

Je suis peut-être biaisé, mais j'ai un très mauvais souvenir des traductions catastrophiques qu'on recevait de Transifex : ne pas pouvoir faire de retours individuels est un gros problème pour la qualité.

Finalement je pense qu'on a un site pour les traductions : Github. Certes c'est close-source. C'est un outil qu'on maîtrise tous, qui permet de relire chaque modification avant sa mise en prod, de faire des retours d'humains à humains, et le processus fonctionne : la traduction avance :

![](https://julienpalard.frama.io/write-the-docs-paris-19/fr_translation_percent.png)

Après si vous voulez faire quelque chose, je ne vous en empêcherai pas.

**Comment by ygingras** [comment]
J'aime le graphique annoté! Pour la doc de Python, le processus actuel n'est pas un bloqueur. Il y a probablement beaucoup d'applications pour lesquelles les traducteurs.trices sont moins avancés techniquement et pour celles si, une interface Web serait très bénéfiques. Pour la doc de Python, l'audience est pas mal avancée. Ceux et celles qui ne maîtrisent pas le workflow git+github y voient quand même dans avantages dans le progrès de leur carrières et l'intérêt pour apprendre le workflow est élevé. Pour ce dernier groupe, la traduction est un bon milieu d'apprentissage pour la suite d'outils git.
