### ISSUE TITLE
Passer sur mailman 3

### ISSUE THREAD

**Issue by Seluj78** [AFPy/infra#9]

**Comment by JulienPalard** [comment]
Alors ça avance, on a https://mm3.afpy.org pour tester, demandez-moi des comptes admin au besoin.

Là je vais me coucher mais l'état actuel est :
- Il peut envoyer des mails
- Il peut presque en recevoir, pour tester, sur lists3.afpy.org, exim4 se plains cependant : `relay not permitted`.

**Comment by Seluj78** [comment]
Top ! merci ! Je veux bien tester un compte admin

**Comment by JulienPalard** [comment]
@Seluj78 fais toi un compte, je te le passerai admin.

**Comment by JulienPalard** [comment]
/usr/share/doc/exim4-config/README.Debian.gz intéressant

**Comment by Seluj78** [comment]
Je me suis cree un compte, j'ai pas encore recu de mail de conf

**Comment by JulienPalard** [comment]
Vu qu'on a des comptes mails (dovecot), des alias, et des mailing lists (lists.afpy.org), je pense qu'on serait plus sereins à ne pas "tout migrer d'un coup".

Proposition de stragégie :
 - On commence par le serveur SMTP, avec la plomberie nécessaire : pour que le mailman l'utilise et le dovecot l'utilisent, et on y configure les alias.
 - On déplace le dovecot.
 - On utilise ce nouveau MTA pour faire pointer vers mailman3 les nouvelles listes et mailman2 les anciennes listes, ce qui nous permet de migrer les listes une par une, doucement, en étudiant comment ça se comporte.

**Comment by JulienPalard** [comment]
https://forum.chatons.org/t/experience-de-migration-de-mailman2-a-mailman3/1516

**Comment by liZe** [comment]
> https://forum.chatons.org/t/experience-de-migration-de-mailman2-a-mailman3/1516

Tu peux prendre une ou deux semaines de vacances pour avoir une chance d’avoir quelque chose qui marche 😒…

J’ai pas trop de temps là, mais si tu peux attendre janvier je pourrai te filer un coup de main.
